[package]
name = "postal-address-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
celes = "2.5.0"
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
